#!/usr/bin/env bash
# Seed path on a PRE-SCOPE (legacy) vault: a simple-mode vault with a
# hand-written glob .sops.yaml and NO .agentkeys-scopes.yaml must upgrade
# smoothly on its first scope mutation — both `scope set` and
# `add-recipient` seed the manifest from current recipients (all = "all").
#
# Regression (the bug this file pins down): the seed pipeline
#   scope_load_manifest "$kv" | yq -P '.' > "$kv/$SCOPES_FILE_NAME"
# let the shell create the (empty) redirect target BEFORE
# scope_load_manifest's missing-file check ran, flipping it into the
# validate-existing-manifest branch — empty file → yq emits null →
# "malformed" death on EVERY legacy vault. Never seen by the other tests
# because their fixtures always write the manifest up front.
set -uo pipefail
source "$(dirname "${BASH_SOURCE[0]}")/lib/vault-fixture.sh"
fixture_require_tools
fixture_new
trap 'rm -rf "$FIXTURE_HOME"' EXIT
source "$REPO/scripts/lib/scope.sh"   # SCOPES_FILE_NAME

fail=0
ck() { [ "$2" = "$3" ] || { echo "FAIL: $1 — expected [$3] got [$2]"; fail=1; }; }
probe() { (cd "$VAULT" && SOPS_AGE_KEY_FILE="$FIXTURE_HOME/keys/$1.txt" sops -d "$2" >/dev/null 2>&1) && echo OK || echo DENIED; }

CORE="$(fixture_keygen core)"; EDGE="$(fixture_keygen edge)"

# Simple-mode vault as the pre-scope CLI left it: hand-written glob
# .sops.yaml covering every yaml for all recipients, no manifest.
build_legacy_vault() {
  VAULT="$1"
  mkdir -p "$VAULT"/{shared,agents,recipients}
  printf '%s\n' "$CORE" > "$VAULT/recipients/core.age.pub"
  printf '%s\n' "$EDGE" > "$VAULT/recipients/edge.age.pub"
  local csv
  csv="$(printf '%s\n%s\n' "$CORE" "$EDGE" | LC_ALL=C sort | paste -sd, -)"
  cat > "$VAULT/.sops.yaml" <<EOF
creation_rules:
  - path_regex: '\.yaml\$'
    age: $csv
EOF
  ( cd "$VAULT"
    git init -q
    echo '{"K":"s"}' > shared/one.yaml
    echo '{"K":"n"}' > agents/nana.yaml
    sops -e -i shared/one.yaml
    sops -e -i agents/nana.yaml
    git add -A && git commit -q -m legacy )
}

# --- 1. scope set on a legacy vault seeds the manifest (all = "all") ---
build_legacy_vault "$FIXTURE_HOME/v1"
before="$(cd "$VAULT" && yq '.sops.age[].recipient' shared/one.yaml | LC_ALL=C sort | paste -sd, -)"
( cd "$VAULT" && AGE_KEY_FILE="$FIXTURE_HOME/keys/core.txt" AGENTKEYS_KEYVAULT="$VAULT" \
    bash "$REPO/agentkeys" scope set core all ) >/dev/null 2>&1 \
  || { echo "FAIL: scope set on legacy vault errored (seed path broken?)"; fail=1; }
ck "manifest seeded"          "$([ -f "$VAULT/$SCOPES_FILE_NAME" ] && echo yes || echo no)" "yes"
ck "core seeded all"          "$(yq -r '.recipients.core // "absent"' "$VAULT/$SCOPES_FILE_NAME" 2>/dev/null)" "all"
ck "edge seeded all"          "$(yq -r '.recipients.edge // "absent"' "$VAULT/$SCOPES_FILE_NAME" 2>/dev/null)" "all"
ck ".sops.yaml regenerated"   "$(grep -c 'GENERATED by agentkeys' "$VAULT/.sops.yaml")" "1"
after="$(cd "$VAULT" && yq '.sops.age[].recipient' shared/one.yaml | LC_ALL=C sort | paste -sd, -)"
ck "recipient set unchanged"  "$after" "$before"
ck "edge still decrypts"      "$(probe edge agents/nana.yaml)" "OK"

# --- 2. add-recipient on a legacy vault seeds, then layers the new machine ---
build_legacy_vault "$FIXTURE_HOME/v2"
THIRD="$(fixture_keygen third)"
( cd "$VAULT" && AGE_KEY_FILE="$FIXTURE_HOME/keys/core.txt" AGENTKEYS_KEYVAULT="$VAULT" \
    bash "$REPO/agentkeys" add-recipient third "$THIRD" ) >/dev/null 2>&1 \
  || { echo "FAIL: add-recipient on legacy vault errored (seed path broken?)"; fail=1; }
ck "manifest seeded (add)"    "$([ -f "$VAULT/$SCOPES_FILE_NAME" ] && echo yes || echo no)" "yes"
ck "core seeded all (add)"    "$(yq -r '.recipients.core // "absent"' "$VAULT/$SCOPES_FILE_NAME" 2>/dev/null)" "all"
ck "edge seeded all (add)"    "$(yq -r '.recipients.edge // "absent"' "$VAULT/$SCOPES_FILE_NAME" 2>/dev/null)" "all"
ck "third recorded all"       "$(yq -r '.recipients.third // "absent"' "$VAULT/$SCOPES_FILE_NAME" 2>/dev/null)" "all"
ck "third decrypts"           "$(probe third shared/one.yaml)" "OK"
ck "core still decrypts"      "$(probe core agents/nana.yaml)" "OK"

[ "$fail" -eq 0 ]
